In [2]:
%cd ..

/Users/kubak/Desktop/mini/sem1/AZ


In [3]:
from src.toeplitz import toeplitz_matvec
import numpy as np

In [4]:
n = 8

t_col = np.array([1, -8, -4, -3, -5, 10, -7, -10], dtype=float)
t_row = np.array([1, -8, -6, -4, -8, -10, 9, 4], dtype=float)

x = np.array([5, 7, 2, -7, -6, -4, 8, -4])
y = toeplitz_matvec(t_col, t_row, x)
print("Wynik mnożenia Toeplitza:", y)

Wynik mnożenia Toeplitza: [-64. 125. -72. -25. -18. -76.  95.  99.]


# Library method

In [6]:
import numpy as np
from scipy.linalg import toeplitz

T = toeplitz(t_row, t_col)

In [7]:
T

array([[  1.,  -8.,  -4.,  -3.,  -5.,  10.,  -7., -10.],
       [ -8.,   1.,  -8.,  -4.,  -3.,  -5.,  10.,  -7.],
       [ -6.,  -8.,   1.,  -8.,  -4.,  -3.,  -5.,  10.],
       [ -4.,  -6.,  -8.,   1.,  -8.,  -4.,  -3.,  -5.],
       [ -8.,  -4.,  -6.,  -8.,   1.,  -8.,  -4.,  -3.],
       [-10.,  -8.,  -4.,  -6.,  -8.,   1.,  -8.,  -4.],
       [  9., -10.,  -8.,  -4.,  -6.,  -8.,   1.,  -8.],
       [  4.,   9., -10.,  -8.,  -4.,  -6.,  -8.,   1.]])

In [8]:
result = T @ x

In [9]:
result

array([-64., 125., -72., -25., -18., -76.,  95.,  99.])

In [10]:
t_col = [4, 1, -2, 3]
t_row = [4, 2, 0, -1]

v = np.array([1, 2, 3, 4])

T = toeplitz(t_col, t_row)

print(T @ v)

[ 4 15 20 18]
